[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028CF7E46F50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7bdce9f29f73d37a61a807e00a7d901c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028CF825C6D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7bdce9f29f73d37a61a807e00a7d901c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028CF825DC90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7bdce9f29f73d37a61a807e00a7d901c